finalized DELETE route for warehouses - tested
kevinlinpt/instock-project-team-1-server pull request #17
Opened 2022-10-19 16:26 UTC by victorarabi

Correct PR request to develop instead of main

2022-10-19 16:30 UTC, kaushal0110 commented
Victor if you can pull the new developed branch and then merge it into ur branch and push code again but dont close or create new PR that will be added to this one automatically

2022-10-19 16:49 UTC, victorarabi commented
hey @kaushal0110 done!

2022-10-19 17:08 UTC, kaushal0110 requested changes

2022-10-19 17:08 UTC, ghost commented on routes/deleteWarehouse/deleteWarehouse.js
> +  warehouses = JSON.parse(fs.readFileSync('./data/warehouses.json'));
So victor here when u r reading the file u r not handling any errors u may get while reading the file like we can console log it to see whats going on

2022-10-19 17:08 UTC, ghost commented on routes/deleteWarehouse/deleteWarehouse.js
> +  inventories = JSON.parse(fs.readFileSync('./data/inventories.json'));
And also readfilesync is a synchronous method which means it will block other code execution until it parses the file and that may be an issue so if you can research about this method and use it “readFile” and handle errors that would be great

2022-10-19 17:08 UTC, ghost commented on routes/deleteWarehouse/deleteWarehouse.js
> +    fs.writeFileSync('./data/warehouses.json', newWarehouses);
Same goes for writefilesync method as i said for readfilesync method

2022-10-19 17:08 UTC, kaushal0110 commented on routes/deleteWarehouse/deleteWarehouse.js
> +deleteWarehouse.delete('/:location', (req, res, next) => {
So instead of getting the warehouse name and then changing it to lowercase can we use the id of warehouse for searching the warehouse from file

2022-10-19 17:08 UTC, kaushal0110 commented on routes/deleteWarehouse/deleteWarehouse.js
> +  let warehouseCheck = warehouses.filter(
So instead if alll the code from here to line 33 we could have simplified it in an easier way i know u r checking first if warehouse exists or not but if we use the find function we can just say if find function not return something then dont proceed else do some thing

2022-10-19 17:26 UTC, victorarabi commented
hi @kaushal0110 I have added the callback to check the functions and changed from filesync to just file. Your other suggestions are not impeditive for the operation of this branch. I won't have time now to modify this and I will ping it as an improvement if we have time.
Please remember that Agile means that we have it working and it is.

2022-10-19 23:40 UTC, victorarabi commented
@kaushal0110 this should be good to go

2022-10-19 23:50 UTC, kaushal0110 commented
> hi @kaushal0110 I have added the callback to check the read/write and changed from filesync to just file. Your other suggestions are not impeditive for the operation of this branch. I won't have time now to modify this and I will ping it as an improvement if we have time.
> Please remember that Agile means that we have it working and it is.

okay but now your branch has merge conflicts because Kevin merged his branches earlier if you could resolve that and push again thnx

2022-10-20 00:06 UTC, victorarabi commented
There should be no conflicts anymore @kaushal0110

2022-10-20 00:09 UTC, kaushal0110 requested changes

2022-10-20 00:09 UTC, kaushal0110 commented on data/warehouses.json
> +<<<<<<< HEAD
I think you left this just remove this I will approve it

2022-10-20 00:14 UTC, kaushal0110 approved these changes

2022-10-20 00:14 UTC, merged